### ISSUE TITLE
Enhancement: Improve Selection mode in Sprite Editor

### ISSUE THREAD

**Issue by TinkerStudio** [pmgl/microstudio#102]
[Discord Link](https://discord.com/channels/593735633130749972/667401412405362688/965032566136639528)  
 
 **Show the X/Y pixel coordinate of the cursor once Selection mode has been activated.** 
 On larger Sprites it is sometimes hard to 'find' the exact 0/0 position. Important to get that one 'on spot' if one would like to use the animation split feature.   
 Also helpful if someone would like to select a sub-frame (if the start/end coordinates are known).

**Comment by Skaruts** [comment]
Might also be useful to have the selection snap to a grid size when holding some key, like ctrl, for example. I think that would help a lot with selecting stuff accurately. You wouldn't actually need to click at (0,0), you could click somewhere near it and the selection would snap to (0,0) and expand to (8,8) or to whatever the grid size might be. 

I suppose the intended grid size could be set at the top, near the sprite size.

Also, I think this might go well with a button to lock the axes proportionally, such that the width and the height are always the same when locked. So you'd only need to set one of them if you just wanted a square grid.

**Comment by pmgl** [comment]
I am closing the issue as the main feature is implemented (X/Y coordinates display). It makes things easier. Also at some point I will revisit the sprite view component, mainly to allow much more zooming on large images.

**Comment by Skaruts** [comment]
@pmgl, more zoom might solve the issue with the `Hold space bar to move view` thing obstructing the bottom pixels of the images. I was meaning to open an issue about it, but I don't know if you'd like to leave it to be solved when you add more zoom.
