### ISSUE TITLE
thread should capture self local variable, like a function does (ms 2.0)

### ISSUE THREAD

**Issue by pmgl** [pmgl/microstudio#129]
```lua
local thread = every 100 do
  if some_condition then thread.stop() end
end
```

**Comment by JmeJuniper** [comment]
Perhaps using the `this` keyword? It would be nice and clean to do `this.pause()` instead of referencing it's own name.

**Comment by pmgl** [comment]
@JmeJuniper this is about capturing the local variable of the thread, so that it can be used from the inner code of the thread. Just like local functions can call themselves recursively, I find it convenient if threads, also when stored in a local variable, can act on themselves.
