### ISSUE TITLE
playMusic() does not loop seamlessly

### ISSUE THREAD

**Issue by saklis** [pmgl/microstudio#137]
microScript's method
`audio.playMusic( name, volume, loop )`
with parameter loop set to `true` does loop, but not seamlessly.

**Comment by pmgl** [comment]
mp3 files cannot loop seamlessly, because the encoder is adding gaps at the beginning and end of the file. The only solution would be to add support for another audio format, like ogg / opus. I am keeping this issue open until a new format is implemented.

**Comment by pmgl** [comment]
Added support for Ogg and FLAC audio formats: https://github.com/pmgl/microstudio/commit/0e1f4720aee9f8138b6842e856186f4aae68a514
