### ISSUE TITLE
[Feature request] Build-in database solution

### ISSUE THREAD

**Issue by saklis** [pmgl/microstudio#147]
I think microStudio would benefit from some build-in solution for data storage.
I would see it as something inspired by SQLite and CastleDB, but simplified and more fitting into microStudio toolkit.

Model: Relational database. Single database per project with multiple tables. No SQL interpreter - microScript API would be used to interact with system.

**Proposed feature list for minimal implementation:**

1. Data types:

- Number
- String

2. Operations:

- Create, Read, Update, Delete

**Extra features:**

1. Data types: Guid

2. Column properties:

- Auto-increment for Number
- Key/Foreign key

**Comment by pmgl** [comment]
That's an interesting suggestion, maybe a bit out of the scope of microStudio though ; I am not sure if you are thinking of a database local to the user or if you mean a global database for the application. The user case can be addressed by using the storage API ; the storage API allows to store structured data (any microScript object, which may contain strings, numbers, lists, other objects...) thus can serve as local database. I am also currently working on the client / server features (online multiplayer) and the server will also have the same storage capability, thus allowing to create a global database for all users of a client/server app.

Also it would be possible to build a database-like / CRUD API on top of the core storage API and to offer it as a public Library.

See https://github.com/pmgl/microstudio/wiki/en-API#storage
