### ISSUE TITLE
Bug with captured outer locals (ms 2.0)

### ISSUE THREAD

**Issue by pmgl** [pmgl/microstudio#151]
```
local test = "ok"
f = function()
  for i=0 to 10
    for j=0 to 10
    end
  end
  print(test)
end
```

prints 10 instead of "ok"

**Comment by pmgl** [comment]
What happened was that the locals stack was corrupted by other locals allocations, at the point where variable `test` is used within the function.

**Comment by Skaruts** [comment]
If you don't mind me asking here: is there any benefit to having local variables at outer scope?

**Comment by pmgl** [comment]
@Skaruts local variables should mostly be used to store temporary values and you generally need them mostly in functions ; the test case here was a dummy test, just to illustrate the bug.

Use cases of the outer locals capture include when you want to create a set of functions with a varying parameter, or more generally when a function needs have some sense of the context where it was created. For example:
```
multiply_functions = []

for i=0 to 10
  multiply_functions[i] = function(x) x*i end
end
```

Another more real-world example:
```
call_at_level_start = []    // this is a list of function we will call when level starts

for i=1 to 100
  local enemy = createEnemy()
  call_at_level_start.push(function() enemy.start() end)
end

(...)

// now when level starts
for f in call_at_level_start
  f()
end
```
