### ISSUE TITLE
Support 'nil' keyword as syntactic sugar for '0'

### ISSUE THREAD

**Issue by Skaruts** [pmgl/microstudio#157]
In the same way the text editor recognizes `true` and `false` as keywords, it could also recognize the keyword `nil`. 

Personally I already use `nil` for setting variables as null, just because it makes them stand out from other variables that are actually numeric. The only thing I feel is missing is having `nil` in a color that stands out, like `true` and `false` do. 

I've been misunderstood about this before, so I should make it clear: I'm not asking for a null type to be added to microscript. I'm suggesting that the text editor could recognize and highlight a keyword.

**Comment by pmgl** [comment]
As you know already, microScript was designed to avoid any use of `nil`, `null`, `none` or `undefined` ; I understand your request but I am reluctant to add more keywords to the language, even if it is just for syntax highlighting. I have two suggestions for you:
- either use `false` to initialize your variables (`false == 0`)
- or maybe you could define `NIL = 0` in your code and use it for that purpose (caps make it stand out maybe!)
