### ISSUE TITLE
keyboard input problem in Lua

### ISSUE THREAD

**Issue by Skaruts** [pmgl/microstudio#165]
`keyboard.press[key]` starts as `nil`, and after `key` has been pressed it's always `0` or `1`. This is a problem because `0` is not false in Lua, so that expression will never be false after `key` is pressed once. It's also a problem because that expression has two states, and you have to test both:
```lua
keyboard.press[key] ~= nil and keyboard.press[key] ~= 0
```
Which is a bit of a hassle.

I haven't tested this with other forms of input, but it may be happening in other places in the engine.

**Comment by pmgl** [comment]
Wouldn't it work to just test equality with 1? Like in:
```lua
if keyboard.press[key] == 1 then
  ...
end
```

**Comment by Skaruts** [comment]
Sorry for the delay. 

Yes, that does work.
