### ISSUE TITLE
i cannot upload files bigger than 5mb

### ISSUE THREAD

**Issue by DeRaNGeR** [pmgl/microstudio#172]
If i try to upload files bigger than 5mb (on web version and local version) i have an infinite waiting process. The file is not uploaded.

Optional: Could be useful to separate limits from web and local installation

**Comment by pmgl** [comment]
I should add an error message when the file is too big ;
I will also remove the limitation for a default install and in standalone mode.

**Comment by pmgl** [comment]
The limit per file is now set to 30 Mb.
