### ISSUE TITLE
Standalone application for RasPi ARM64

### ISSUE THREAD

**Issue by lee-yunseok** [pmgl/microstudio#183]
Raspberry Pi user here, the microstudio works well with npm online, so I want to try it with a standalone app. Can you provide ARM64 DEB binary?

**Comment by pmgl** [comment]
Hey, sorry I did not get back to you on this. I have no plans to provide a 64bits build yet indeed. However, there is a "recipe" here on how to build your own standalone app, in case you would be interested:

https://microstudio.dev/community/articles/recipe-standalone-microstudio-app/243/

I think at least one person has successfully built it for RPi 64 in the past.

**Comment by lee-yunseok** [comment]
Thank you, it working perfectly. Also I'm sorry I didn't search it from the community. Happy New Year :)
