### ISSUE TITLE
Release 23.05.25 Changelog Inconsistency

### ISSUE THREAD

**Issue by Xorcist77** [pmgl/microstudio#203]
For the release:

https://github.com/pmgl/microstudio/releases/tag/23.05.25

the changelog link goes to:

https://github.com/pmgl/microstudio/blob/master/static/doc/en/changelog.md

which shows:

![image](https://github.com/pmgl/microstudio/assets/14016854/f942d0bf-75e2-4a6a-979b-3d4a9b9b751d)

but within the standalone downloaded application it shows:

![image](https://github.com/pmgl/microstudio/assets/14016854/bfda0c9f-c265-4a0a-8c9b-702d006b1ae2)

which is a bit confusing, seeing as how one has newer changelog entries than the other, in fact I was surprised to not find releases for 23.06.13 or 23.07.04.

**Comment by pmgl** [comment]
Well I am doing releases when there are significant changes - and also when I can!
Whenever you crucially need a new online feature in the standalone, note that you can easily produce your own standalone build, following this "recipe": https://microstudio.dev/community/articles/recipe-standalone-microstudio-app/243/
