### ISSUE TITLE
API: Extends to support mobile sensor

### ISSUE THREAD

**Issue by HomineLudens** [pmgl/microstudio#60]
It might be interesting to allow microStudio to support a variety of mobile sensors such as inclinometer and gps data.

Actually I consider this a very low in priority, nevertheless it can open a wide range of possibilities.

**Comment by pmgl** [comment]
I don't think I will add an official API for this for now, maybe it is too specific to mobile devices ; let's just wait for someone to implement a microStudio lib for this, leveraging the new ability to embed JavaScript in your project :-)

I am closing the issue.
