### ISSUE TITLE
Bug "I invited myself"

### ISSUE THREAD

**Issue by Kureshik** [pmgl/microstudio#76]
![image](https://user-images.githubusercontent.com/79392961/151711578-df8dc335-6a15-4086-9da2-2016e7e87526.png)
(Click for better quality)

This has already happened twice. I don't know what to attribute this bug to.
(I didn't invite anyone, I just refreshed the page)
When I updated again, it disappeared.

**Comment by pmgl** [comment]
This happens when you reload microStudio right after having edited something ; you are displayed as being another editor of the file, as if you were editing it from another tab or from another browser. It should be fixed with my next commit.
