### ISSUE TITLE
bug: console input history

### ISSUE THREAD

**Issue by Kureshik** [pmgl/microstudio#78]
In the console, you can view the input history by pressing the up arrow.
If you press the down arrow in an empty console it will be this:
![image](https://user-images.githubusercontent.com/79392961/151730568-2e45b771-a1d2-4533-b6b0-523c28c7abfe.png)

**Comment by pmgl** [comment]
Something I learnt in the process about JavaScript:

```
null >= 0
true
null == 0
false
null > 0
false
```
