### ISSUE TITLE
Editor: Intellisense pop-up

### ISSUE THREAD

**Issue by TinkerStudio** [pmgl/microstudio#84]
Working at the end of a long line, or at the bottom of your source code the Intellisense pop-up sometimes covers the edit area.

![image](https://user-images.githubusercontent.com/61921707/152864408-b5b9e1d1-9de3-41a1-8ad6-042ad844dee9.png)

**Comment by pmgl** [comment]
I did my best! I may rework this when I will integrate Monaco.
